car/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^detail/(\d+)$', detail, name='car_detail'),
    url(r'^addFav/(\d+)$', addFav, name= 'addFav'),
    url(r'^compare/', compare, name="compare"),
    url(r'^get_cars/$', get_cars_by_brand, name='get_cars_by_brand'),
    url(r'^deletFav/(\d+)$',deleteFav,name='deleteFav'),
    url(r'^filter/$', filter_cars, name='filter'),
    url(r'^get_filter_cars/', get_filter_cars, name='filter_cars'),
]

mc_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from car.views import index as s_index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('authen.urls')),
    url(r'^car/', include('car.urls',namespace='car')),
    url(r'^usercenter/', include('usercenter.urls', namespace='usercenter')),
]

car/models.py
from django.db import models
from authen.models import *
# Create your models here.
# 车辆的车型


class CarType(models.Model):
    type_name = models.CharField(max_length=50, verbose_name='类型名称')
    type_desc = models.CharField(max_length=50, verbose_name='类型描述', null=True)

    def __str__(self):
        return self.type_name

    class Meta:
        verbose_name_plural = verbose_name = '车辆类型'
# 车辆的品牌


class CarBrand(models.Model):
    barnd_name = models.CharField(max_length=50, verbose_name='品牌名称')
    barnd_desc = models.CharField(
        max_length=50, verbose_name='品牌描述', null=True)

    def __str__(self):
        return self.barnd_name

    class Meta:
        verbose_name_plural = verbose_name = '车辆品牌'
# 专区


class CarSpecialArea(models.Model):
    spec_area_name = models.CharField(max_length=50, verbose_name='专区名称')
    spec_area_desc = models.CharField(
        max_length=100, verbose_name='专区描述', null=True)

    def __str__(self):
        return self.spec_area_name

    class Meta:
        verbose_name_plural = verbose_name = '车辆专区'

# 车辆的信息


class Car(models.Model):

    # CarId = models.CharField(max_length=20,primary_key=True,verbose_name='车辆id')
    car_name = models.CharField(max_length=100, verbose_name='车辆名称')
    car_price = models.DecimalField(
        max_digits=7, decimal_places=2, verbose_name='车辆价格')
    car_body_work = models.CharField(max_length=40, verbose_name='车身结构')
    car_l_w_h = models.CharField(max_length=40, verbose_name='长/宽/高')
    car_engine = models.CharField(max_length=40, verbose_name='发动机')
    car_gear_box = models.CharField(max_length=40, verbose_name='变速箱')
    car_drive_way = models.CharField(max_length=40, verbose_name='驱动方式')
    car_fuel_type = models.CharField(max_length=20, verbose_name='燃料类型')
    car_oil_cons = models.CharField(max_length=20, verbose_name='综合油耗')
    car_color = models.CharField(max_length=220, verbose_name='车辆配色')
    car_href_pic = models.ImageField(
        upload_to='static/cars/hrefs/', verbose_name='车辆图片')
    car_ld_pic = models.ImageField(
        upload_to='static/cars/liangdian', verbose_name='车型亮点')
    car_is_active = models.BooleanField(verbose_name='在售', default=True)
    car_type = models.ForeignKey(CarType, verbose_name='车型')
    car_brand = models.ForeignKey(CarBrand, verbose_name='品牌')
    car_spec_area = models.ForeignKey(
        CarSpecialArea, verbose_name='所属专区', null=True)

    def __str__(self):
        return self.car_name

    class Meta:
        verbose_name = verbose_name_plural = '车辆信息'


class CarImage(models.Model):
    car_img = models.ImageField(
        upload_to='static/cars/car_images/', verbose_name='车辆图片')
    car = models.ForeignKey(Car, verbose_name='所属车辆')

    def __str__(self):
        return self.car.car_name

    class Meta:
        verbose_name = verbose_name_plural = '车辆图片'

# 预约单信息
class ResevationList(models.Model):
    active = (
        ('0', '等待处理'),
        ('1', '预约成功'),
    )
    resevation_list_name = models.CharField(max_length=50,verbose_name = '预约单名称')
    a_user_name = models.CharField(max_length=50,verbose_name = '预约用户名')
    a_user_telephone = models.CharField(max_length=20,verbose_name ='预约用户联系方式')
    sale_name = models.CharField(max_length=50,verbose_name ='销售员姓名')
    sale_telephone = models.CharField(max_length=20,verbose_name ='销售员联系方式')
    meet_place = models.CharField(max_length=100,verbose_name='预约地点')
    resevation_time = models.DateTimeField(auto_now = True,verbose_name='预约单生成时间')
    meet_time = models.DateField(verbose_name='预约时间')
    resevation_car = models.ForeignKey(Car, verbose_name='预约的车辆')
    resevation_is_active = models.BooleanField(
        default=False, verbose_name='预约成功')
    resevation_uname = models.ForeignKey(
        User, verbose_name='所属用户', null=True)
    def __str__(self):
        return self.resevation_list_name

    class Meta:
        verbose_name_plural = verbose_name = '预约单'
#收藏夹详细信息 
class Favorite(models.Model):
    favorite_car = models.ManyToManyField(Car, verbose_name='收藏的车辆')
    favorite_user = models.OneToOneField(User, verbose_name='所属用户')

    def __str__(self):
        return self.favorite_user.username

    class Meta:
        verbose_name = verbose_name_plural = '收藏夹'

class ImportData(models.Model):
    file = models.FileField(upload_to='File', verbose_name=u'车辆信息')

    class Meta:
        verbose_name = verbose_name_plural = '导入车辆数据'
        ordering = ['file']

    def __str__(self):
        return str(self.file)

class ImportDataFro(models.Model):
    file = models.FileField(upload_to='File', verbose_name=u'车辆类型')

    class Meta:
        verbose_name = verbose_name_plural = '导入车辆类型品牌专区'
        ordering = ['file']

    def __str__(self):
        return str(self.file)

class ImportDataImages(models.Model):
    file = models.FileField(upload_to='File', verbose_name=u'车辆类型')

    class Meta:
        verbose_name = verbose_name_plural = '导入车辆详细图片'
        ordering = ['file']

    def __str__(self):
        return str(self.file)

# 轮播类
class Carousel(models.Model):
    pic = models.ImageField(upload_to='static1/carousels/', verbose_name='轮播图片')
    intro1 = models.CharField(max_length=200, verbose_name='标语1')
    intro2 = models.CharField(max_length=200, verbose_name='标语2')
    is_use = models.BooleanField(default=False, verbose_name='是否显示')

    def __str__(self):
        return self.intro1
    
    class Meta:
        verbose_name = verbose_name_plural = '轮播管理'


class CarPrice(models.Model):
    car = models.OneToOneField(Car, verbose_name='所属车辆')
    shoufu = models.IntegerField('首付（元）', default=4920)
    yuegong = models.IntegerField('月供（元）', default=3547)
    qishu = models.IntegerField('期数', default=12)
    weikuan = models.IntegerField('尾款', default=120000)

    def __str__(self):
        return self.car.car_name
    
    class Meta:
        verbose_name = verbose_name_plural = '分期价格管理'

car/views.py
from django.shortcuts import render, redirect
from .models import *
from car.models import *
from django.http import JsonResponse, HttpResponseRedirect
import random
from usercenter.models import Notice
# Create your views here.


def index(request):
    # cars = Car.objects.all()
    # return render(request, 'index.html', locals())
    rm_area = CarSpecialArea.objects.get(spec_area_name='热卖专区')
    jd_area = CarSpecialArea.objects.get(spec_area_name='经典专区')
    zx_area = CarSpecialArea.objects.get(spec_area_name='最新车型')
    cars = Car.objects.all()
    carousels = Carousel.objects.filter(is_use=True)
    rm_cars = Car.objects.filter(car_spec_area=rm_area)
    cars1 = rm_cars[::3]
    cars2 = rm_cars[1::3]
    cars3 = rm_cars[2::3]
    return render(request, 'index.html', locals())


def detail(request, car_id):
    if request.method == 'GET':
        user = request.user
        exist = False
        car = Car.objects.get(id=car_id)
        if user.is_authenticated:
            # car = Car.objects.get(id=car_id)
            # print(car)
            fav = Favorite.objects.get(favorite_user=user)
            result = fav.favorite_car.filter(id=car_id)
            # print(result)
            if result.exists():
                exist = True
        a = Car.objects.values('id')
        b = []
        for i in a:
            b.append(i['id'])
        interestNumber = random.sample(b, 3)
        interestcar = []
        for i in interestNumber:
            interestcar.append(Car.objects.get(id=i))
            # print(interestcar)
        car_imgs = CarImage.objects.filter(car=car)
        return render(request, 'detail.html', locals())
    if request.method == 'POST':
        r_name = request.POST.get('r_name', '')
        a_u_name = request.POST.get('a_u_name', '')
        a_u_phone = request.POST.get('a_u_phone', '')
        sale_name = request.POST.get('sale_name', '')
        sale_phone = request.POST.get('sale_phone', '')
        r_place = request.POST.get('r_place', '')
        r_date = request.POST.get('r_date', '')
        car_name = Car.objects.filter(id=car_id)[0]
        ResevationList.objects.create(
            resevation_list_name=r_name,
            a_user_name=a_u_name,
            a_user_telephone=a_u_phone,
            sale_name=sale_name,
            sale_telephone=sale_phone,
            meet_place=r_place,
            meet_time=r_date,
            resevation_time=r_date,
            resevation_car=car_name,
            resevation_uname=request.user)
        Notice.objects.create(user=request.user, content='用户'+request.user.username+' 已预约 '+car_name.car_name+' .')
        return HttpResponseRedirect("/car/detail/"+str(car_id))
    else:
        return HttpResponse("预约失败！")


def addFav(request, car_id):
    user = request.user
    if user.is_authenticated:

        fav = Favorite.objects.filter(favorite_user=user)
        if not fav:
            Favorite.objects.create(favorite_user=user)
        fav = Favorite.objects.get(favorite_user=user)
        add_car = Car.objects.get(id=car_id)
        fav.favorite_car.add(add_car)
        Notice.objects.create(user=request.user, content='用户 '+request.user.username+' 已收藏 '+add_car.car_name)
        return redirect('/car/detail/' + car_id)
    else:
        return redirect('/login')


def compare(request):
    car1_id = request.GET.get('car1', '')
    car2_id = request.GET.get('car2', '')
    car3_id = request.GET.get('car3', '')
    car4_id = request.GET.get('car4', '')
    brands = CarBrand.objects.all()
    try:
        car1 = Car.objects.get(id=car1_id)
    except Exception as e:
        pass
    try:
        car2 = Car.objects.get(id=car2_id)
    except Exception as e:
        pass
    try:
        car3 = Car.objects.get(id=car3_id)
    except Exception as e:
        pass
    try:
        car4 = Car.objects.get(id=car4_id)
    except Exception as e:
        pass

    return render(request, 'duibi.html', locals())


def get_cars_by_brand(request):
    brand_id = request.POST.get('brand', '')
    cars = Car.objects.filter(car_brand=brand_id)
    objs = []
    for car in cars:
        obj = {}
        obj['id'] = car.id
        obj['name'] = car.car_name
        objs.append(obj)
    return JsonResponse({"res": objs})


def deleteFav(request, num_id):
    user = request.user
    fav = Favorite.objects.get(favorite_user=user)
    delete_car = Car.objects.get(id=num_id)
    fav.favorite_car.remove(delete_car)
    Notice.objects.create(user=request.user, content='用户 '+request.user.username+' 已取消收藏 '+delete_car.car_name)
    return redirect('/car/detail/' + num_id)


def filter_cars(request):
    # c_b = CarBrand.objects.get(barnd_name=a)
    # cars = Car.objects.filter(car_brand=c_b)
    brands = CarBrand.objects.all()
    types = CarType.objects.all()
    return render(request, 'filter.html', locals())


def get_filter_cars(request):
    kw = request.GET.get('kw', '')
    if kw:
        from django.db.models import Q
        cars = Car.objects.filter(
            Q(car_brand__barnd_name__contains=kw) |
            Q(car_type__type_name__contains=kw) |
            Q(car_name__contains=kw)
        )
    else:
        a = request.GET.get('a', '')
        b = request.GET.get('b', '')
        c = request.GET.get('c', '')
        d = request.GET.get('d', '')
        e = request.GET.get('e', '')
        if d == '':
            cars = Car.objects.filter(car_brand__barnd_name__contains=a,
                                      car_type__type_name__contains=e,
                                      )
        else:
            import re
            ran = re.match(r'(\d+)-(\d+)\w+', d)
            if not ran:
                cars = Car.objects.filter(car_brand__barnd_name__contains=a,
                                          car_type__type_name__contains=e,
                                          car_price__gt=d[:2]
                                          )
            else:
                cars = Car.objects.filter(car_brand__barnd_name__contains=a,
                                          car_type__type_name__contains=e,
                                          car_price__gt=ran.group(1),
                                          car_price__lt=ran.group(2))
    data = []
    for car in cars:
        obj = {}
        obj['name'] = car.car_name
        obj['price'] = car.car_price
        obj['pic'] = '/' + str(car.car_href_pic)
        obj['id'] = car.id
        data.append(obj)
    return JsonResponse({'data': data})

car/templates/duibi.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="{%static 'car/css/compare.css'%}">
    <!-- <link rel="stylesheet" href="{%static 'car/css/style.css'%}"> -->
    <title></title>
    <link rel="stylesheet" href="{%static 'bootstrap/css/bootstrap.css'%}">

    <link rel="stylesheet" href="{% static 'car/css/zerogrid.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'car/css/style.css' %}"> -->
    <link rel="stylesheet" href="{% static 'car/css/responsiveslides.css' %}">
    <style>
    .pr li a {
            width: 100px;
            text-align: center;
        }
    </style>
    </style>
    
</head>

<body>
   <header class="bg-theme">
    <div class="wrap-header zerogrid">
        <div class="row">
            <div id="cssmenu" style="margin-right: 13%;">
            
                <ul class="pr">
                   <li class='active'><a href="/car">首页</a></li>
                   <li><a href="/car/filter/">车辆</a></li>
                    {%if request.user.is_authenticated%}
                    <li><a id="mytar" href="/usercenter">我的</a>
                        <ul class="my">
                            <li style="height: 42px;"><a style="width: 100px; line-height: 42px; vertical-align: middle;" href="/usercenter">个人中心</a></li>
                            <li style="height: 60px;"><a style="width: 100px; line-height: 42px; vertical-align: middle;" href="/logout">退出登录</a></li>
                        </ul>
                        </li>
                    <script>
                        $(function(){
                            $("ul.pr > li").hover(function(){
                                $(this).children("ul").show("fast");
                            }, function(){
                                $(this).children("ul").hide("slow");
                            })
                        })
                    </script>
                    <!-- <li><a href="/logout">dengchu</a></li> -->
                    {%else%}
                    <li><a href="/login">尊贵登录</a></li>
                   {%endif%}
                   <!-- <li><a href="contact.html">预约看车</a></li> -->
                </ul>
            </div>
            <a href='index.html' class="logo"><img src="{% static 'car/images/logo.png' %}" /></a>
        </div>
    </div>
</header>
    <div id="div1">
        <img src="images/deng.jpg" alt="" height="30px" width="40px" style="float:left;margin-top:10px;"> 以下信息仅供参考，不构成任何买卖协议，实际情况以店内销售情况为准
    </div>
    <div id="div2">
        <table align="center" border="1px">
            <thead>
                <h2>&nbsp;&nbsp;&nbsp;&nbsp;车辆信息对比</h2></thead>
            <tr>
                <td class="car">
                    <center>
                        <h3>对比车型</h3>
                    </center>
                </td>
                <td class="car">
                    <div class="div3" id="car1">
                        <input type="hidden" id="chooice-car1" value=""> {%if car1%}
                        <!-- <div style="position: absolute; width:35px; display: inline-block; float: right; background: #000;"></div> -->
                        <span><img class="close" src="{%static 'car/images/close.png'%}" alt="关闭" style="width: 35px;float: right; position: absolute;"></span>
                        <img src="/{{car1.car_href_pic}}" style="width: 278px;" alt=""> {%else%}
                        <img class="jiahao" src="{% static 'car/images/jiahao.PNG' %}" data-toggle="modal" data-target="#myModal" alt="">
                        <!-- 在这里加入汽车的图片 -->
                        <img class="tu" src="" alt="" onerror="this.style.display='none'"> {%endif%}
                    </div>
                </td>
                <td class="car">
                    <div class="div3" id="car2">
                        <input type="hidden" id="chooice-car2" value=""> {%if car2%}
                        <span><img class="close" src="{%static 'car/images/close.png'%}" alt="关闭" style="width: 35px;float: right; position: absolute;"></span>
                        <img src="/{{car2.car_href_pic}}" style="width: 278px;" alt=""> {%else%}
                        <img class="jiahao" src="{% static 'car/images/jiahao.PNG' %}" data-toggle="modal" data-target="#myModal" alt="">
                        <!-- 在这里加入汽车的图片 -->
                        <img class="tu" src="" alt="" onerror="this.style.display='none'"> {%endif%}
                    </div>
                </td>
                <td class="car">
                    <div class="div3" id="car3">
                        <input type="hidden" id="chooice-car3" value=""> {%if car3%}
                        <span><img class="close" src="{%static 'car/images/close.png'%}" alt="关闭" style="width: 35px;float: right; position: absolute;"></span>
                        <img src="/{{car3.car_href_pic}}" style="width: 278px;" alt=""> {%else%}
                        <img class="jiahao" src="{% static 'car/images/jiahao.PNG' %}" data-toggle="modal" data-target="#myModal" alt="">
                        <!-- 在这里加入汽车的图片 -->
                        <img class="tu" src="" alt="" onerror="this.style.display='none'"> {%endif%}
                    </div>
                </td>
                <td class="car">
                    <div class="div3" id="car4">
                        <input type="hidden" id="chooice-car4" value=""> {%if car4%}
                        <span><img class="close" src="{%static 'car/images/close.png'%}" alt="关闭" style="width: 35px;float: right; position: absolute;"></span>
                        <img src="/{{car4.car_href_pic}}" style="width: 278px;" alt=""> {%else%}
                        <img class="jiahao" src="{% static 'car/images/jiahao.PNG' %}" data-toggle="modal" data-target="#myModal" alt="">
                        <!-- 在这里加入汽车的图片 -->
                        <img class="tu" src="" alt="" onerror="this.style.display='none'"> {%endif%}
                    </div>
                </td>
            </tr>
            <tr>
                <td style="border-right:0px solid;">
                    <center>
                        <h3>基本信息</h3></center>
                </td>
            </tr>
            <tr>
                <td class="infoName">车型</td>
                <td>{{car1.car_name}}</td>
                <td>{{car2.car_name}}</td>
                <td>{{car3.car_name}}</td>
                <td>{{car4.car_name}}</td>
            </tr>
            <tr>
                    <td class="infoName">价格（万元）</td>
                    <td>{{car1.car_price}}</td>
                    <td>{{car2.car_price}}</td>
                    <td>{{car3.car_price}}</td>
                    <td>{{car4.car_price}}</td>
            </tr>
            <tr>
                <td class="infoName">车身结构</td>
                <td>{{car1.car_body_work}}</td>
                <td>{{car2.car_body_work}}</td>
                <td>{{car3.car_body_work}}</td>
                <td>{{car4.car_body_work}}</td>
            </tr>
            <tr>
                <td class="infoName">长/宽/高</td>
                <td>{{car1.car_l_w_h}}</td>
                <td>{{car2.car_l_w_h}}</td>
                <td>{{car3.car_l_w_h}}</td>
                <td>{{car4.car_l_w_h}}</td>
            </tr>
            <tr>
                <td class="infoName">发动机</td>
                <td>{{car1.car_engine}}</td>
                <td>{{car2.car_engine}}</td>
                <td>{{car3.car_engine}}</td>
                <td>{{car4.car_engine}}</td>
            </tr>
            <tr>
                <td class="infoName">变速箱</td>
                <td>{{car1.car_gear_box}}</td>
                <td>{{car2.car_gear_box}}</td>
                <td>{{car3.car_gear_box}}</td>
                <td>{{car4.car_gear_box}}</td>
            </tr>
            <tr>
                <td class="infoName">驱动方式</td>
                <td>{{car1.car_drive_way}}</td>
                <td>{{car2.car_drive_way}}</td>
                <td>{{car3.car_drive_way}}</td>
                <td>{{car4.car_drive_way}}</td>
            </tr>
            <tr>
                <td class="infoName">燃料类型</td>
                <td>{{car1.car_fuel_type}}</td>
                <td>{{car2.car_fuel_type}}</td>
                <td>{{car3.car_fuel_type}}</td>
                <td>{{car4.car_fuel_type}}</td>
            </tr>
            <tr>
                <td class="infoName">综合油耗</td>
                <td>{{car1.car_oil_cons}}</td>
                <td>{{car2.car_oil_cons}}</td>
                <td>{{car3.car_oil_cons}}</td>
                <td>{{car4.car_oil_cons}}</td>
            </tr>
            <tr>
                <td class="infoName">车辆配色</td>
                <td>{{car1.car_color}}</td>
                <td>{{car2.car_color}}</td>
                <td>{{car3.car_color}}</td>
                <td>{{car4.car_color}}</td>
            </tr>
<!--             <tr>
                <td class="infoName">油箱容量</td>
                <td>{{car1.car_name}}</td>
                <td>{{car2.car_name}}</td>
                <td>{{car3.car_name}}</td>
                <td>{{car4.car_name}}</td>
            </tr> -->
        </table>
    </div>
    <!-- 模态框（Modal） -->
    <style>
    .modal {
        padding-top: 200px;
    }
    </style>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        &times;
                    </button>
                    <h4 class="modal-title" id="myModalLabel">
                    选择车辆
                </h4>
                </div>
                <div class="modal-body">
                    <label for="chooice-brand">选择品牌</label>
                    <select name="brand" id="chooice-brand">
                        {% for brand in brands%}
                        <option value="{{brand.id}}">{{brand.barnd_name}}</option>
                        {%endfor%}
                    </select>
                    <label for="chooice-car">选择车型</label>
                    <select name="car" id="chooice-car">
                    </select>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭
                    </button>
                    <button type="button" id="selected-car" class="btn btn-primary" data-dismiss="modal">
                        确认
                    </button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal -->
    </div>
    <script src="{%static 'bootstrap/jquery/jquery.js'%}"></script>
    <script src="{%static 'bootstrap/js/bootstrap.js'%}"></script>
    <script>
    $(function() {
        var first = $("#chooice-brand")[0].value;
        get_cars(first);
    })
    $("#chooice-brand").change(function() {
        get_cars(this.value);
    })

    function get_cars(brand_id) {
        $("#chooice-car").empty();
        $.ajax({
            url: "{%url 'car:get_cars_by_brand' %}",
            data: {
                'brand': brand_id,
                'csrfmiddlewaretoken': '{{csrf_token}}'
            },
            type: 'POST',
            success: function(res) {
                obj = $("#chooice-car");
                data = res.res;
                data.forEach(function(e) {
                    obj.append("<option value='" + e.id + "'>" + e.name + "</option>");
                });
            }
        });
    };
    $(".jiahao").click(function() {
        selected = this.parentNode;
    })
    $("#selected-car").click(function() {
        selected.childNodes[1].value = $("#chooice-car").val();
        var car1 = $("#chooice-car1").val()||get_param("car1");
        var car2 = $("#chooice-car2").val()||get_param("car2");
        var car3 = $("#chooice-car3").val()||get_param("car3");
        var car4 = $("#chooice-car4").val()||get_param("car4");
        var href = "car1=" + car1 + "&car2=" + car2 + "&car3=" + car3 + "&car4=" + car4;
        href = window.location.pathname + "?" + href;
        window.location.href = href;
    })

    function get_param(param) {
        var referrer = document.location.href;
        var index = referrer.indexOf("?");
        var params = referrer.substring(index + 1);
        var reg = new RegExp("(^|&)" + param + "=([^&]*)(&|$)");
        var r = params.match(reg);
        if (r != null) 
            return decodeURI(r[2]);
        else
        return "";
    }
    $(".close").click(function(){
        href = clean_param(this.parentNode.parentNode.id);
        href = window.location.pathname + "?" + href;
        window.location.href = href;
    })
    function clean_param(param){
        var referrer = document.location.href;
        var index = referrer.indexOf("?");
        var params = referrer.substring(index + 1);
        var reg = new RegExp("(^|&)" + param + "=([^&]*)(&|$)");
        return params.replace(reg, '$1'+param+'='+'$3');
    }
    </script>


    {% include 'footer.html' %}
</body>

</html>

car/templates/footer.html
<div class="footer_wy">
<footer>
    <div class="zerogrid">
        <div class="wrap-footer">
            <div class="row">
                <h3>联系我们</h3>
                <span>电话 / 88886666 </span></br>
                <span>邮箱 / info@domain.com  </span></br>
                <span>地址 / 西北农林科技大学 </span></br>
                <span><strong>Copyright &copy; 2018　All rights reserved</strong></span>
            </div>
        </div>
    </div>
</footer>
</div>