car/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^detail/(\d+)$', detail, name='car_detail'),
    url(r'^addFav/(\d+)$', addFav, name= 'addFav'),
    url(r'^compare/', compare, name="compare"),
    url(r'^get_cars/$', get_cars_by_brand, name='get_cars_by_brand'),
    url(r'^deletFav/(\d+)$',deleteFav,name='deleteFav'),
    url(r'^filter/$', filter_cars, name='filter'),
    url(r'^get_filter_cars/', get_filter_cars, name='filter_cars'),
]

mc_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from car.views import index as s_index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('authen.urls')),
    url(r'^car/', include('car.urls',namespace='car')),
    url(r'^usercenter/', include('usercenter.urls', namespace='usercenter')),
]

usercenter/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^info/$', info, name='info'),
    url(r'^yuyue/$', ReserverList, name='yuyue'),
    url(r'^dianping/$', dianping, name='dianping'),
    url(r'^safe/$', safe, name='safe'),
    url(r'^mima/$', mima, name='mima'),
    url(r'^fav/$', fav, name='fav'),
    url(r'^xiaoxi/$', xiaoxi, name='xiaoxi'),
    url(r'^deleteFavo/([0-9]+)$', deleteFavo, name = 'deleteFavo'),
    url(r'^duibi$', duibi_view, name = 'duibi'),
    url(r'^zijin/$', zijin, name='zijin'),
    url(r'^jilu/$', jilu, name='jilu'),
    url(r'^goumai/$', goumai, name='goumai'),
    url(r'^bycar/(\d+)/$', buy_car, name='buycar'),
]

usercenter/models.py
from django.db import models
from authen.models import *
from car.models import *

# Create your models here.
# 消息记录
class Notice(models.Model):
    user = models.ForeignKey(User, verbose_name='所属用户')
    content = models.CharField(max_length=200, verbose_name='通知内容')
    n_time = models.DateTimeField(auto_now=True, verbose_name='通知时间')

    def __str__(self):
        return self.user.username
    
    class Meta:
        verbose_name = verbose_name_plural = '消息记录'


# 用户账户信息
class UserAccount(models.Model):
    user = models.OneToOneField(User, verbose_name='所属用户')
    yue = models.IntegerField('账户余额', default=0)

    def __str__(self):
        return self.user.username
    
    class Meta:
        verbose_name = verbose_name_plural = '用户账户'


# 账户记录
class AccountRecord(models.Model):
    user = models.ForeignKey(User, verbose_name='所属用户')
    p_type = models.CharField(max_length=30, verbose_name='类型')
    p_intro = models.CharField(max_length=200, verbose_name='附加说明')
    amount = models.IntegerField('交易金额')
    p_time = models.DateTimeField(auto_now=True, verbose_name='操作时间')

    def __str__(self):
        return self.user.username
    
    class Meta:
        verbose_name = verbose_name_plural = '账户记录'


# 购买记录
class PayRecord(models.Model):
    car = models.ForeignKey(Car, verbose_name='车型')
    user = models.ForeignKey(User, verbose_name='所属用户')
    is_paied = models.BooleanField(verbose_name='是否付清', default=True)
    p_type = models.CharField(max_length=30, verbose_name='付款方式')
    cost = models.IntegerField('本次支付金额', null=True)
    costed = models.IntegerField('已支付金额', null=True)
    pay_time = models.DateTimeField('付款时间',auto_now=True)

    def __str__(self):
        return self.user.username
    
    class Meta:
        verbose_name = verbose_name_plural = '购买记录'

usercenter/views.py
from django.shortcuts import render,redirect
from authen.models import *
from car.models import *
from .models import *
from django.contrib import auth
from django.http import HttpResponse
import os
# Create your views here.


def index(request):
    user = request.user
    print(user.image)
    return render(request, 'usercenter/index.html')


def info(request):
    if request.method == 'GET':
        return render(request, 'usercenter/info.html')
    elif request.method == 'POST':
        upfile = request.FILES.get('pic', None)
        if upfile:
            houzhui = upfile.name.split('.')[-1]
            disk_path = 'static1/upload/usericon/'
            filepath = os.path.join(disk_path, str(request.user.id)+'.'+houzhui)
            des = open(filepath, 'wb+')
            for chunk in upfile.chunks():
                des.write(chunk)
                des.close()
            user = request.user
            user.image = filepath
            user.save()
        
        return redirect('/usercenter/info/')



def ReserverList(request):
    reser_list = ResevationList.objects.filter(resevation_uname=request.user)
    return render(request, 'usercenter/yuyue.html', locals())

def dianping(request):
    return render(request, 'usercenter/dianping.html')

def safe(request):
    return render(request, 'usercenter/safe.html')


def mima(request):
    if request.method == "POST":
        user = request.user
        old = request.POST.get('oldPwd')
        new1 = request.POST.get('newPwd')
        new2 = request.POST.get('confirmPwd')
        print(old)
        if old == "" or new1 == "" or new2 == "":
            result = '请输入完整信息'
        elif new1 != new2:
            result = '请确保密码和确认密码一致'
        elif user.check_password(old):
                user.set_password(new1)
                user.save()
                result = '修改密码成功'
        else:
            result = '原始密码错误'
        print(result)
        return render(request, 'usercenter/mima.html', locals())
    else:
        user = request.user
        return render(request, 'usercenter/mima.html')

def fav(request):
    s = Favorite.objects.get(favorite_user=request.user)
    # print(s)
    allCar = s.favorite_car.all()
    # print(allCar[1].car_href_pic)
    return render(request, 'usercenter/fav.html', locals())

def xiaoxi(request):
    notices = Notice.objects.filter(user=request.user)[::-1]
    count = len(notices)
    return render(request, 'usercenter/xiaoxi.html', locals())

def deleteFavo(request, num_id):
    user = request.user
    fav = Favorite.objects.get(favorite_user=user)
    delete_car = Car.objects.get(id=num_id)
    fav.favorite_car.remove(delete_car)
    Notice.objects.create(user=request.user, content='用户 '+request.user.username+' 已取消收藏 '+delete_car.car_name)
    return redirect('/usercenter/fav')

def duibi_view(request):
    cars = request.POST.getlist('car')
    # print(cars)
    result = []
    for car in cars:
        i = Car.objects.get(id=car)
        result.append(i)
    # print(result)
    return render(request, 'usercenter/duibi.html', locals())


def zijin(request):
    if request.method == 'GET':
        return render(request, 'usercenter/zijin.html')
    else:
        m = request.POST.get('addmoney', '')
        if m != '':
            m = int(m)
            uz = request.user.useraccount
            uz.yue = uz.yue + m
            uz.save()
            AccountRecord.objects.create(user=request.user, p_type='充值', p_intro='用户账户充值',
                amount=m)
        return redirect('/usercenter/zijin/')


def jilu(request):
    records = AccountRecord.objects.filter(user=request.user)[::-1]
    count = len(records)
    return render(request, 'usercenter/jilu.html', locals())


def goumai(request):
    records = PayRecord.objects.filter(user=request.user)[::-1]
    count = len(records)
    return render(request, 'usercenter/goumai.html', locals())


def buy_car(request, carid):
    car = Car.objects.get(id=carid)
    ua = request.user.useraccount
    if ua.yue < car.car_price*10000:
        return HttpResponse('余额不足！')
    ua.yue = ua.yue - car.car_price*10000
    ua.save()
    AccountRecord.objects.create(user=request.user,
    p_type='消费',
    p_intro = '购买 '+car.car_name,
    amount = car.car_price*10000)
    PayRecord.objects.create(car = car,
    user=request.user,
    p_type='全款',
    )
    return HttpResponse('购买成功！')

usercenter/templates/usercenter/dianping.html
{%extends 'usercenter/index.html'%}

{%block title%}
{%endblock%}

{%block content%}
<!--right-->
<div class="centers_mr">
<div class="public_m1">
     <div class="public_m2">我的点评</div>
     <!--一个订单信息-->
     <div class="public_m5">
       <table border="0" cellspacing="0" cellpadding="0">
         <tbody>
          <tr style=" border-bottom:1px solid #000">       
           <th class="olist1">预约单编号</th>       
           <th class="olist2">预约时间</th>       
           <th class="olist4">预约地点</th>
           <th class="olist4">结束时间</th>
           <th class="olist4">状态</th>       
         </tr>    
         <tr>     
           <td>2016102111523538</td>     
           <td>2016-10-21 12:03</td>
           <td>城南</td>     
           <td>2016-10-21 12:03</td>        
           <td>正在点评</td>
         </tr>
       </tbody>
     </table>
   </div>
   <!--评价星级-->
   <div class="pjxingji_m">
     <ul>
       <li>
         <em>客服态度：</em>
         <input type="radio" name="cpzl_m1">
         <img src="images/1xing.png"/>
         <input type="radio" name="cpzl_m1">
         <img src="images/2xing.png">
         <input type="radio" name="cpzl_m1">
         <img src="images/3xing.png"/>
         <input type="radio" name="cpzl_m1">
         <img src="images/4xing.png">
         <input type="radio" name="cpzl_m1">
         <img src="images/5xing.png">
       </li>
       <li>
         <em>服务质量：</em>
         <input type="radio" name="cpzl_m2">
         <img src="images/1xing.png"/>
         <input type="radio" name="cpzl_m2">
         <img src="images/2xing.png"/>
         <input type="radio" name="cpzl_m2">
         <img src="images/3xing.png"/>
         <input type="radio" name="cpzl_m2">
         <img src="images/4xing.png"/>
         <input type="radio" name="cpzl_m2">
         <img src="images/5xing.png"/>
       </li>
       <li>
         <em>试车环境：</em>
         <input type="radio" name="cpzl_m3">
         <img src="images/1xing.png"/>
         <input type="radio" name="cpzl_m3">
         <img src="images/2xing.png"/>
         <input type="radio" name="cpzl_m3">
         <img src="images/3xing.png"/>
         <input type="radio" name="cpzl_m3">
         <img src="images/4xing.png"/>
         <input type="radio" name="cpzl_m3">
         <img src="images/5xing.png"/>
       </li>
     </ul>
   </div>
   <!--我的牛评-->
   <div class="my_lm">
     <em>我的评价：</em>
     <textarea></textarea>
   </div>
   <!--选择上传文件-->
   <div class="myinput_lm">
     <em>上传图拍：</em>
     <input type="file">
     <input type="checkbox">
     <i>匿名上传</i>
   </div>
   <a href="#" class="public_m3">提交</a>
 </div>
</div>
{%endblock%}

usercenter/templates/usercenter/fav.html
{%extends 'usercenter/index.html'%}

{%block title%}
{%endblock%}

{%block content%}
{%load static%}
<!--right-->
<div class="centers_mr">
<div class="public_m1">
  <div class="fa_title">
                
    <div class="left_width" >收藏车辆</div>
    <div class="right_width">
    </div>
  </div>
  <div class="public_m6">
    <div class="all_product">
      <!-- <form name="choose_pk" method="POST" action = '/usercenter/duibi'> -->
        {%csrf_token%}
        {% for car in allCar %} 
      <div class="product">
          <div class="product_info">
              <a href="{%url 'usercenter:deleteFavo' car.id %}"><img src="{%static 'usercenter/images/heart.png'%}" style="float:right;top: 5px; right: 0; width: 25px;height: 30px;margin-top: 5px;"></a>
              <img src="/{{car.car_href_pic}}" alt="product1" style="width: 100%;height: 200px;">
              <h3 class="product_title">{{car.car_name}}</h3>
              <!-- <span>base recommend</span> -->
              <span class="product_price">指导价{{car.car_price}}万元</span>
              <!-- <input type="button" name="咨询" value="立即咨询" class="buy_button"> -->
              <!-- <input type="checkbox" name="car" value="{{car.id}}">加入对比 -->
             <!-- <input type="submit" class="buy_button" value="对比"> -->
             <a href="{%url 'car:compare' %}?car1={{car.id}}"><button class="btn btn-lg btn-success">对比</button></a>

          </div>
      </div>
        {%endfor%}
      <!-- <div class="compare_btn"> -->
      <!-- <a href="{%url 'usercenter:duibi' %}"><button type="button" class="compare_btn">对比</button></a> -->
      <!-- <input type="submit" class="compare_btn" value="对比"> -->
      <!-- </div> -->
    <!-- </form> -->
    </div>
    <img src="{%static 'usercenter/images/danmgydxm.png'%}"/>
  </div>    
 
 
</div>

    <!--页脚-->
</div>
{%endblock%}

 <!-- <img src="{%static 'usercenter/images/zshy.png'%}"/> -->

usercenter/templates/usercenter/goumai.html
{%extends 'usercenter/index.html'%}

{%block title%}
{%endblock%}

{%block content%}
{%load static%}
<!--right-->
<div class="centers_mr">
<div class="public_m1">
	<div class="public_m2">购买记录</div>

	<!--充值提现-->
	<div class="chongzhi_htxm">
		<a href="javascript:void(0);">记录数<font>({{count}})</font></a>
		<!-- <a href="#">商家消息<font>(2)</font></a> -->
	</div>
	<!--全选和删除-->
	<!-- <div class="chice_allm">
		<input type="checkbox">
		<i>全选</i>
		<span>删除</span>
	</div> -->
	<!--一个订单信息-->
	<div class="public_m5">
		<table border="0" cellspacing="0" cellpadding="0">
			<tbody>
				<tr style=" border-bottom:1px solid #000">       
                    <th class="olist1">车辆价格</th>
                    <th class="olist2">付款方式</th>              
                    <th class="olist3">车型</th>
                    <th class="olist4">操作时间</th>
				</tr>
				{%for r in records%}
				<tr>		
						<td>{{r.car.car_price}}万元</td>
                        <td>{{r.p_type}}</td>
                        <td>{{r.car.car_name}}</td>
                        <td>{{r.pay_time}}</td>
					</tr>
				{%endfor%}
				
				<!-- <tr>		
					<td><a href="#">木木小店</a></td>	 
					<td>吃饭了么...</td>		
					<td>2016/06/06 20:30</td>
					<td><a href="#" style=" margin-right:6px">查看</a><a href="#">删除</a></td>
				</tr> -->
			</tbody>
		</table>
	</div>
	<!--当没有东西时的东西-->
	<div class="public_m6">
		<img src="{% static 'usercenter/images/danmgydxm.png' %}"/>
	</div>
</div>
</div>
<!--页脚-->
{%endblock%}

usercenter/templates/usercenter/index.html
{%load static%}
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>{%block title%}会员中心{%endblock%}</title>

  <link rel="stylesheet" type="text/css" href="{%static 'usercenter/css/center.css'%}">
  <link rel="stylesheet" type="text/css" href="{%static 'usercenter/css/style.css'%}">
  <link rel="stylesheet" href="{%static 'bootstrap/css/bootstrap.css'%}">
  <script src="{%static 'usercenter/js/jquery-1.8.3.min.js'%}"></script>
  <!-- <script src="{%static 'usercenter/js/index2.js'%}"></script> -->
  <!-- <link rel="stylesheet" type="text/css" href="css/center.css"> -->
  <style>
  .pr li a {
            width: 100px;
            text-align: center;
        }
    </style>
  </style>
  
</head>
<body>
  <header class="bg-theme">
    <div class="wrap-header zerogrid">
        <div class="row">
            <div id="cssmenu" style="margin-right: 13%;">
            
                <ul class="pr">
                   <li class='active'><a href="/car">首页</a></li>
                   <li><a href="/car/filter/">车辆</a></li>
                    {%if request.user.is_authenticated%}
                    <li><a id="mytar" href="/usercenter">我的</a>
                      <ul class="my">
                          <li style="height: 42px;"><a style="width: 100px; line-height: 42px; vertical-align: middle;" href="/usercenter">个人中心</a></li>
                          <li style="height: 60px;"><a style="width: 100px; line-height: 42px; vertical-align: middle;" href="/logout">退出登录</a></li>
                      </ul>
                      </li>
                    <script>
                        $(function(){
                            $("ul.pr > li").hover(function(){
                                $(this).children("ul").show("fast");
                            }, function(){
                                $(this).children("ul").hide("slow");
                            })
                        })
                    </script>
                    <!-- <li><a href="/logout">dengchu</a></li> -->
                    {%else%}
                    <li><a href="/login">尊贵登录</a></li>
                   {%endif%}
                   <!-- <li><a href="contact.html">预约看车</a></li> -->
                </ul>
            </div>
            <a href='/' class="logo"><img src="{% static 'car/images/logo.png' %}" /></a>
        </div>
    </div>
</header>

 <!--当前位置-->
 <div class="now_positionm">
  <span>当前位置：</span><a href="#">首页></a><a href="#">个人中心</a>
</div>
<!--centers kaobian_xsd-->
<div class="centers_m">
    <!--清除浮动-->
  <div class="clear_sm"></div>
  <!--left-->
  <div class="centers_ml">
   <!--头像-->
  <div class="center_header">
    {%comment%}
       TODO：将下方的 图像和名字用用户的信息加载
    {%endcomment%}
     <a href="{%url 'usercenter:index'%}"><img src="/{{request.user.image}}" alt=""></a>
     <em>您好，<font>{{request.user.username}}</font></em>
   </div>
   <!--列表go-->
   <div class="centers_listm">
     <div class="centers_listm_one">
       <img src="{%static 'usercenter/images/zshy.png'%}"/>
       <a href="{%url 'usercenter:index'%}"><em>个人中心</em></a>
     </div>
     <!--一条开始-->
     <div class="centers_listm_one_in">
      <img src="{%static 'usercenter/images/shezhi.png'%}"/>
      <em>资料管理</em>
      <b></b>
    </div>
    <span class="gjszmdm">
      <a href="{%url 'usercenter:info'%}" class="center_in_self"><font>信息资料</font></a>
    </span>
    <!--一条开始-->
    <div class="centers_listm_one_in">
        <img src="{%static 'usercenter/images/ddgl.png'%}"/>
        <em>资金管理</em>
        <b></b>
      </div>
      <span class="gjszmdm">
        <a href="{%url 'usercenter:zijin'%}" class="center_in_self"><font>我的资金</font></a>
        <a href="{%url 'usercenter:jilu'%}" class="center_in_self"><font>交易记录</font></a>
        <!-- <a href="{%url 'usercenter:dianping'%}" class="center_in_self"><font>我的点评</font></a> -->
      </span>
    <!--一条开始-->
    <div class="centers_listm_one_in">
      <img src="{%static 'usercenter/images/ddgl.png'%}"/>
      <em>订单管理</em>
      <b></b>
    </div>
    <span class="gjszmdm">
      <a href="{%url 'usercenter:yuyue'%}" class="center_in_self"><font>我的预约</font></a>
      <a href="{%url 'usercenter:goumai'%}" class="center_in_self"><font>购买记录</font></a>
      <!-- <a href="{%url 'usercenter:dianping'%}" class="center_in_self"><font>我的点评</font></a> -->
    </span>
    <!--一条开始-->
    <div class="centers_listm_one_in">
      <img src="{%static 'usercenter/images/suo.png'%}"/>
      <em>账户安全</em>
      <b></b>
    </div>
    <span class="gjszmdm">
      <a href="{%url 'usercenter:safe'%}" class="center_in_self"><font>账户安全</font></a>

      <a href="{%url 'usercenter:mima'%}" class="center_in_self"><font>密码修改</font></a>
    </span>    
    <!--一条开始-->
    <div class="centers_listm_one_in">
      <img src="{%static 'usercenter/images/wdssc.png'%}"/>
      <em>收藏管理</em>
      <b></b>
    </div>
    <span class="gjszmdm">
     <a href="{%url 'usercenter:fav'%}" class="center_in_self"><font>车辆收藏</font></a>
   </span>    
   <!--一条开始-->
   <div class="centers_listm_one_in">
    <img src="{%static 'usercenter/images/myfridend.png'%}"/>
    <em>消息管理</em>
    <b></b>
  </div>
  <span class="gjszmdm">
   <a href="{%url 'usercenter:xiaoxi'%}" class="center_in_self"><font>我的消息</font></a>
 </span>
</div>
<script type="text/javascript">
        $(function(){//第一步都得写这个
            $(".centers_listm_one_in").click(function(){
       $(this).next(".gjszmdm").slideToggle().siblings("gjszmdm").slideUp()
     });
        })
  </script>
</div>
{%block content%}
<!--right-->
<div class="centers_mr">
  <h1 class="welcom_tm">欢迎您  
    <font> {{request.user.username}} </font>！您上次登录时间为 {{request.user.last_login}}</h1>
    <!--一条开始-->
    <div class="public_m1">
     <div class="public_m2">个人中心</div>
     <!--照片和内容--> 
     <div class="zp_nrm">
       <!--left-->
       <div class="zp_nrm_l">
         <img src="/{{request.user.image}}"/>

       </div>
       <!--right-->
       <div class="zp_nrm_r">

         <p><em>用户名：</em><i>{{request.user.username}}</i></p>
         <p><em>邮箱：</em><i>{{request.user.email}}</i></p>
         <!-- <p><em>手机号：</em><i>{{request.user.phone}}</i></p> -->
         <!-- <p><em>性别：</em><input type="radio" name="sex" class="sex_m"><i>保密</i><input type="radio" name="sex" class="sex_m"><i>男</i><input type="radio" name="sex" class="sex_m"><i>女</i></p> -->
         <!-- <p><em>性别：</em><i>{{request.user.gender}}</i></p>
         <p><em>地址:  &nbsp;</em><i>{{request.user.address}}</i></p> -->
       </div>
     </div>
   </div>
</div>
{%endblock%}

<div class="footer_wy">
  <footer>
      <div class="zerogrid">
          <div class="wrap-footer">
              <div class="row">
                  <h3>联系我们</h3>
                  <span>电话 / 88886666 </span></br>
                  <span>邮箱 / info@domain.com  </span></br>
                  <span>地址 / 西北农林科技大学 </span></br>
                  <span><strong>Copyright &copy; 2018　All rights reserved</strong></span>
              </div>
          </div>
      </div>
  </footer>
</div>

<script src="{%static 'bootstrap/jquery/jquery.js'%}"></script>
<script src="{%static 'bootstrap/js/bootstrap.js'%}"></script>
</body>
</html>   

usercenter/templates/usercenter/info.html
{%extends 'usercenter/index.html'%} {%block title%} {%endblock%} {%block content%}
<!--right-->
<div class="centers_mr">
	<h1 class="welcom_tm">欢迎您
		<font> ！</font>
	</h1>
	<div class="public_m1">
		<div class="public_m2">信息管理</div>
		<!--照片和内容-->
		<div class="zp_nrm">
			<div class="zp_nrm_r">
				<form action="" method="post" enctype="multipart/form-data">
					<p>
						<em>头像：</em>
						<i>
							<img src="/{{request.user.image}}" alt="" height="40px" width="40px">
						</i>
						<a href="javascript:void(0);">
							<label for="usericon">点击更换</label>
						</a>
					</p>
					<div style="display: none">
						<input type="file" name="pic" id="usericon">
					</div>
					{%csrf_token%}
					<p>用户名：{{request.user.username}}</p>
					<p>
						<em>邮箱：</em>
						<i>{{request.user.email}}</i>
					</p>
					<!-- <p><em>手机号：</em><i>{{request.user.phone}}</i></p>
					<p><em>性别：</em><input type="radio" name="sex" class="sex_m"><i>保密</i><input type="radio" name="sex" class="sex_m"><i>男</i><input type="radio" name="sex" class="sex_m"><i>女</i></p>
					<p><em>地址：</em><i>{{request.user.address}}</i><a href="#">点击修改</a></p> -->
					<!-- <a href="" class="public_m3">保存修改</a> -->
					<input type="submit" class="public_m3" value="保存修改">
				</form>
			</div>
		</div>
	</div>
	<!--页脚-->
	{%endblock%}

usercenter/templates/usercenter/jilu.html
{%extends 'usercenter/index.html'%}

{%block title%}
{%endblock%}

{%block content%}
{%load static%}
<!--right-->
<div class="centers_mr">
<div class="public_m1">
	<div class="public_m2">交易记录</div>

	<!--充值提现-->
	<div class="chongzhi_htxm">
		<a href="javascript:void(0);">记录数<font>({{count}})</font></a>
		<!-- <a href="#">商家消息<font>(2)</font></a> -->
	</div>
	<!--全选和删除-->
	<!-- <div class="chice_allm">
		<input type="checkbox">
		<i>全选</i>
		<span>删除</span>
	</div> -->
	<!--一个订单信息-->
	<div class="public_m5">
		<table border="0" cellspacing="0" cellpadding="0">
			<tbody>
				<tr style=" border-bottom:1px solid #000">       
                    <th class="olist1">类型</th>
                    <th class="olist2">附加说明</th>              
                    <th class="olist3">交易金额</th>
                    <th class="olist4">操作时间</th>
				</tr>
				{%for r in records%}
				<tr>		
						<td>{{r.p_type}}</td>
                        <td>{{r.p_intro}}</td>
                        {%ifequal r.p_type '充值'%}
                        <td style="color: green;">+{{r.amount}}元</td>    
                        {%else%}
                        <td style="color: red;">-{{r.amount}}元</td>    
                        {%endifequal%}
                        
                        <td>{{r.p_time}}</td>
						
					</tr>
				{%endfor%}
				
				<!-- <tr>		
					<td><a href="#">木木小店</a></td>	 
					<td>吃饭了么...</td>		
					<td>2016/06/06 20:30</td>
					<td><a href="#" style=" margin-right:6px">查看</a><a href="#">删除</a></td>
				</tr> -->
			</tbody>
		</table>
	</div>
	<!--当没有东西时的东西-->
	<div class="public_m6">
		<img src="{% static 'usercenter/images/danmgydxm.png' %}"/>
	</div>
</div>
</div>
<!--页脚-->
{%endblock%}

usercenter/templates/usercenter/mima.html
{%extends 'usercenter/index.html'%}

{%block title%}
{%endblock%}

{%block content%}
<!--right-->
<div class="centers_mr">
<div class="public_m1">
 <div class="public_m2">密码修改</div>
 <!--提示信息-->	
 <div class="tip_notem">
   <ul>
     <li>1.请牢记登录密码</li>
     <li>2.如果丢失密码，可以通过绑定的手机或邮箱找到</li>
   </ul>
 </div>
 <div class="public_m4">
   <p>
     <em>原密码：</em>
     <input type="text" style=" height:23px; border:1px solid #eaeaea; width:140px">
   </p>
   <p>
     <em>新的密码：</em>
     <input type="text" style=" height:23px; border:1px solid #eaeaea; width:140px">
   </p>
   <p>
     <em>确认密码：</em>
     <input type="text" style=" height:23px; border:1px solid #eaeaea; width:140px">
   </p>
   <a href="#" class="public_m3">确认修改</a>
 </div>
</div> 
</div>
{%endblock%}